version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432